# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: "Validate PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Validate semantic PR title"
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.0.0
        # https://github.com/amannn/action-semantic-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://mazer.dev/en/git/best-practices/git-semantic-commits/
          # https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          types: |
            build
            ci
            chore
            docs
            fix
            enh
            feat
            refact
            revert
            perf
            style
            test
          scopes: |
            deps
            i18n
          requireScope: false

      - name: "Label PR"
        uses: srvaroa/labeler@bf262763a8a8e191f5847873aecc0f29df84f957 # v1.14.0
        # https://github.com/srvaroa/labeler
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
